services:
  frontend:
    build: ./frontend
    env_file:
      - .env.local
    ports:
      - 5000:5000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3002
      
  backend:
    build: ./backend
    ports:
      - 3002:3002

    
