services:
  frontend:
    build: ./frontend
    env_file:
      - .env.local
    ports:
      - 5000:5000
    environment:
      - NEXT_PUBLIC_API_URL=https://api.ExtractionMapping.coffeeinc.in
      
  backend:
    build: ./backend
    ports:
      - 5001:5001

    
